name: golang-setup

on:
  push:
    branches: [ "master", "feature/CI-CD" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./... -coverprofile cover.out && go tool cover -func cover.out

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -C cmd -o bin/quiz