name: golang-setup

on:
  push:
    branches: [ "master", "feature/CI-CD" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./... -coverprofile cover.out && go tool cover -func cover.out

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -C cmd -o bin/quiz
      - name: Setup Git
        uses: actions/setup-git@v4
      - name: Commit and push binary
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add bin/quiz
            git commit -m "Add binary"
            git push